server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/users/**
